hazelcast:
    rest.enabled: false
    memcache.enabled: false
    jmx.enabled: false
    shutdownhook.enabled: false
    
    logging.type: slf4j
    
    initial.min.cluster.size: 0
    
    operation.generic.thread.count: -1
    operation.thread.count: -1
    
    io.input.thread.count: 5
    io.output.thread.count: 7 # equal to number of core pool executor
    
    socket.receive.buffer.size: 1024
    socket.send.buffer.size: 1024

forceLocalMemberToBeSafe.timeout: 60
sharedGlobalTask.timeout: 30
